FROM maven AS builder

WORKDIR /app

# copie du pom.xml et telechargement des dependances
COPY pom.xml .
RUN mvn dependency:go-offline

# copie les fichiers sources et execution de la construction
COPY src ./src
RUN mvn package -DskipTests


FROM openjdk

WORKDIR /app

COPY --from=builder /app/target/spring-security-0.0.1-SNAPSHOT.jar .