version: '3.8'

services:
  dbmyql:
    container_name: bdd
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql  
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: admin
      MYSQL_PASSWORD: admin
    networks:
      - mysql-phpmyadmin
  phpmyadmin:
    depends_on:
      - dbmyql
    image: phpmyadmin
    restart: always
    ports:
      - "8077:80"
    environment:
      PMA_HOST: dbmyql
    networks:
      - mysql-phpmyadmin
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    ports: 
      - "8090:80"  
    depends_on:
      - dbmyql:
      - other_service: true
       
  frontend:
  build:
    context: ./frontend
    dockerfile: dockerfile 
  ports:
    - "3000:80"  
  depends_on:
    - backend

networks:
  mysql-phpmyadmin:
    driver: bridge
volumes:
  db_data: